require('mini.pick').setup()
require('mini.extra').setup()

vim.keymap.set('n', '<leader>f', MiniPick.builtin.files, { desc = 'search files' })
vim.keymap.set('n', '<leader>b', MiniPick.builtin.buffers, { desc = 'search files' })
vim.keymap.set('n', '<leader>/', MiniPick.builtin.grep_live, { desc = 'search live grep' })
vim.keymap.set('n', '<leader>x', MiniExtra.pickers.commands, { desc = 'search commands' })
vim.keymap.set('n', '<leader>r', function() MiniExtra.pickers.lsp({scope='references'}) end, { desc = 'search lsp references' })
vim.keymap.set('n', '<leader>s', function() MiniExtra.pickers.lsp({scope='workspace_symbol_live'}) end, { desc = 'search lsp workspace symbol live' })
vim.keymap.set('n', '<leader>S', function() MiniExtra.pickers.lsp({scope='workspace_symbol'}) end, { desc = 'search workspace symbol' })
vim.keymap.set('n', '<leader>d', MiniExtra.pickers.diagnostic, { desc = 'search finder' })
vim.keymap.set('n', '<leader>l', MiniExtra.pickers.buf_lines, { desc = 'search finder' })
